### ISSUE TITLE
Combine notebooks working with backends and compiler

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#100]
See the new tutorials here: 
https://github.com/jaygambetta/qiskit-tutorial/pull/10

Remove appendix/advanced_qiskit/compiling_and_running.ipynb - @jaygambetta was going to combine this with reference/tools/working_with_backends.ipynb

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by jaygambetta** [comment]
This has been done in pr #118 but i still want to redo that section after qiskit version 0.5
