### ISSUE TITLE
Getting started tutorial is too complicated

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#103]
This requires the installation of latex and image creation packages that are quite big. 
I think we should place instruction of how to use latex and pdf packages in the advanced topics, not in the getting started

https://github.com/QISKit/qiskit-tutorial/blob/master/1_introduction/getting_started.ipynb
## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by ajavadia** [comment]
The circuit visualization cell has to be updated. I'm not sure where I have to push changes since some big refactoring seems to be taking place. But that entire cell should be replaced by this:
```
from qiskit.tools.visualization import circuit_drawer
circuit_drawer(circuit)
```
Can you make this change?

**Comment by ajavadia** [comment]
This does not alleviate the dependency on pdflatex. But it is cleaner (that entire function has now moved to the SDK itself).
We can put this in a separate tutorial on visualization later.

**Comment by jaygambetta** [comment]
I have updated the new getting started. It is much simpler but i want to get the visualizations.
