### ISSUE TITLE
Avoid using local_qasm_simulator for 10 qubits or more

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#105]
## Description

The `local_qasm_simulator` is too slow and not efficient for simulating 10 or more qubits. 
The alternative is to use the new `ibmqx_hpc_qasm_simulator` or `ibmqx_qasm_simulator`. 

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by ajavadia** [comment]
In the next release the local_qasm_simulator will be a fast c++ simulator, and can handle large qubits.
I think it is preferable to use local simulators that don't require internet connection.

**Comment by rraymondhp** [comment]
Thanks! My concern is that the simplest introductory in the tutorial, quantum_emoticon.py uses 16 qubit simulator. When run with the local_qasm_simulator, it takes several minutes while it takes just several seconds with the online simulators. 

For this reason, I would like to keep this open until the next release of qiskit-sdk-py.

**Comment by jaygambetta** [comment]
Lets close this as it is related to the QISKit Core. The functionality will not change.

**Comment by kwyip** [comment]
I encounter `LookupError: backend "ibmqx_hpc_qasm_simulator" not found.` when I try to use `ibmqx_hpc_qasm_simulator`.
