### ISSUE TITLE
Error message while running Maxcut in ibmqx5 - 16 qubit from classical_optimization in application examples

### ISSUE THREAD

**Issue by venkatbgs** [QISKit/qiskit-tutorial#109]
## Description

While trying to run simple Maxcut (for 4 qubits) with ibmqx5, get the following error:  

WARNING:IBMQuantumExperience.IBMQuantumExperience:Got a 400 code response to  {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. The qasm has no measures.","code":"QASM_NOT_VALID","statusCode":400}}

The same notebook runs ok with the simulator (local_qasm_simulator). I ran the classical_optimization example in 4_applications folder. 

## Your Environment

* Tutorial branch (stable/master): Master
* QISKit SDK version: 0.4.8
* Python version: 3.5.3

**Comment by rraymondhp** [comment]
Hi @venkatbgs 
We are working to rewrite the tutorials. I suspect that this is due to the change in compiler of real devices. 
Please allow us some time to fix.

**Comment by jaygambetta** [comment]
@rraymondhp can you looking into this.

**Comment by rraymondhp** [comment]
@venkatbgs  Please use this notebook. It will be merged to the tutorial once Jay and Anna reviewed it. 
https://github.com/rraymondhp/qiskit-tutorial/blob/d84e43dcc81e02333714153eabd82a6a54a04942/appendix/algo_app/classical_optimization.ipynb

**Comment by jaygambetta** [comment]
@rraymondhp what is the status of this

**Comment by rraymondhp** [comment]
We found a bug in creating Hamiltonian in the example. My colleagues is working on it. Hopefully we can push the correct version next week.

**Comment by rraymondhp** [comment]
@venkatbgs  

Sorry for keeping you waiting. 

Please update your qiskit with `pip install -U qiskit` and get the latest tutorial of maxcut from the tutorial.
