### ISSUE TITLE
[Checking]The qubits got permuted when running with real devices

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#130]
## Description

There is an issue of real-devices that permute the order of qubits. This will be solved with the next release of qiskit-sdk-py. Until that release, we have to provide a workaround of fixing the qubit order. 

## Your Environment

* QISKit version:
* Python version:

**Comment by rraymondhp** [comment]
This apparently has been fixed with the version 0.4.12 of qiskit-sdk-py.

**Comment by jaygambetta** [comment]
i dont think this is an issue. Did you put an initial_layout in

**Comment by rraymondhp** [comment]
It has been solved with 0.4.13.
