### ISSUE TITLE
Strange error with simulators

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#136]
## Description

When running the following code, I got `backend ... not available` error. 
```
backend = "ibmqx_hpc_qasm_simulator"
shots = 1000
results = Q_program.execute([circuitName], backend=backend, shots=shots)
answer = results.get_counts(circuitName)

plot_histogram(answer)
```

But when I queried the available backends, with pprint as below, I can run the code. 
```
from pprint import pprint

pprint(Q_program.available_backends())
pprint(Q_program.get_backend_status('ibmqx_hpc_qasm_simulator'))
pprint(Q_program.get_backend_status('ibmqx_qasm_simulator'))


backend = "ibmqx_hpc_qasm_simulator"
shots = 1000
results = Q_program.execute([circuitName], backend=backend, shots=shots)
answer = results.get_counts(circuitName)

plot_histogram(answer)
```

## Your Environment

* IBMQuantumExperience                   1.9.0    
* qiskit                                 0.4.12   
* python 3.6.2

**Comment by t-imamichi** [comment]
This patch removed `qiskit.backends.discover_remote_backends(self.__api)` in `QuantumProgram.set_api`. That's why users cannot run any program on the remote simulators without calling `available_backends`.
https://github.com/QISKit/qiskit-sdk-py/pull/363/commits/ace23ec7094a770fe567f9402e49e7cf86e75d24

**Comment by jaygambetta** [comment]
@rraymondhp  can you check with 0.4.13 this should be fixed now.

**Comment by rraymondhp** [comment]
@jaygambetta  Thanks! I have checked that it works with producing deprecated warnings. 

I will close this issue once I have confirmed all tutorials work.

**Comment by rraymondhp** [comment]
Confirmed that the latest version is compatible with old tutorials.
