### ISSUE TITLE
Print the correct versions of qiskit, IBM Quantum Experience, and python version

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#137]
## Description

At the end of tutorials, add the following codes (or, compatible lines that do better). 
The current version check just print the content of `requirements.txt` that might not be true anymore. 
```
! pip list | grep "qiskit"
! pip list | grep "IBMQuantumExperience"
! python --version
```
## Your Environment

* QISKit version:
* Python version:

**Comment by jaygambetta** [comment]
@rraymondhp can you please put all these together #135
