### ISSUE TITLE
Generating Equilibrium file

### ISSUE THREAD

**Issue by SerkanGuldal** [QISKit/qiskit-tutorial#139]
## Description
What is the easiest way to generate Equilibrium.txt files?

## Your Environment

* QISKit version: 0.4.12
* Python version: Python 3.6.5

**Comment by rraymondhp** [comment]
What do you mean by equilibrium.txt files?

**Comment by SerkanGuldal** [comment]
ansatz. In the following folder, LiHEquilibrium.txt is stored.
qiskit-tutorial/reference/approximate/LIH/

Likewise, I want to calculate Li2, so I need the equilibrium (It is named here like that) file for Li2.

If I am mistaken please let me know.

**Comment by antoniomezzacapo** [comment]
Hi,
generating qubit Hamiltonians from general molecular configurations is currently not an available feature.

**Comment by antoniomezzacapo** [comment]
Yes, we are considering adding it so stay tuned for next releases. Thanks
