### ISSUE TITLE
Problems with superposition and entanglement notebook

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#140]
The current notebook of `superposition_and_entanglement.ipynb` does not work as desired if run on remote backends.

https://github.com/QISKit/qiskit-tutorial/blob/master/reference/qis/superposition_and_entanglement.ipynb

## Description

1. The current notebook runs ok with local simulators, but when `backend=ibmqx_qasm_simulator` it cannot be run anymore unless the `lowest_pending_jobs()` function is called. 

2. The circuit_drawer does not work (the image is misalign). Also, please provide the installation instruction of required packages for Linux, Mac, and Windows. 
![misalign_drawing](https://user-images.githubusercontent.com/15240898/38853285-bc5d29ca-4257-11e8-84a3-e79f339f2870.png)

## Your Environment

* QISKit version: 0.4.13
* Python version: 3.6.2

**Comment by jaygambetta** [comment]
i dont see why we want the user to be using the online and if they want they can do write backend = "ibmqx_qasm_simulator". 

Also i dont see what is wrong with the image. If is is the cropping make and issue just on that and give the machine you are on. 

also @ajavadia is working on that as an extension to the INSTALL in #95.
