### ISSUE TITLE
Replace local_qasm_simulator with local_qiskit_simulator

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#142]
## Description

For local simulation of 10 qubits or more, the `local_qiskit_simulator` should be used. 
Here is a comparison of running quantum_emoticon tutorial: `local_qiskit_simulator` takes 3.6 seconds vs `local_qasm_simulator` takes more than 1200 seconds.
```
import time
start_time = time.time()

backend = "local_qiskit_simulator" 
#backend = "local_qasm_simulator" 
shots_sim = 1000
results_sim = qp.execute(["smiley_writer"], backend=backend, shots = shots_sim, wait=5, timeout=300)
stats_sim = results_sim.get_counts("smiley_writer")

print("--- %s seconds ---" % (time.time() - start_time))

plot_histogram(stats_sim)
```

## Your Environment

* QISKit version: 0.4.13
* Python version: 3.6
MacBookAir MacOSX with 8GM RAM and 1.6GHz i5

**Comment by ajavadia** [comment]
Don't change this. In v0.5, `local_qasm_simulator` will automatically select the faster simulator, if it is installed.

**Comment by rraymondhp** [comment]
Noted. But for classical optimization and the above hello word program it can take more than 20 minutes to run the program. I suggest you to use `local_qiskit_simulator` as the generic name. In particular, because qiskit sounds familiar than qasm. 

Anyway, isn't it we are using qobj instead of qasm?

**Comment by jaygambetta** [comment]
closing as with qiskit 0.5 this is not longer an issue
