### ISSUE TITLE
Provide a way for checking the tutorials when a new qiskit version is released

### ISSUE THREAD

**Issue by diego-plan9** [QISKit/qiskit-tutorial#144]
## Description

After some discussion spawned from #135 and the tutorials as a whole, it seems that having an easy, ideally single-shot way of checking if the tutorials are working against a new version of `qiskit` (or other dependencies in general) would facilitate keeping them in sync.

As a simple approach, a command that can be executed locally by a tutorial repository maintainer and clearly outputs which ones are working and which ones are not seems a good compromise. We can make use of the Python test framework for paving the way towards having a more integrated system in the future if needed.

## Your Environment

* QISKit version:
* Python version:

**Comment by rraymondhp** [comment]
This has been solved thanks to @diego-plan9
