### ISSUE TITLE
How to use classical "if" control

### ISSUE THREAD

**Issue by taojiastanford** [QISKit/qiskit-tutorial#18]
I was trying the teleportation circuit, which requires control using classical registers. The code is the following:
`include "qelib1.inc";
qreg q[5];
creg c0[1];
creg c1[1];
creg c2[1];

h q[0];
t q[0];
h q[0];
cx q[0],q[1];
h q[0];
measure q[0] -> c0[0];
measure q[1] -> c1[0];
if (c0==1)
	x q[2];
if (c1==1)
	z q[2];
measure q[2] -> c2[0];
`
And I got error:

> Error in line 14: Operations are disabled

Which refers to the "if" operation. How should I use a classical register to control a quantum gate?

**Comment by jaygambetta** [comment]
@taojiastanford what backend are you using. If is not supported in real devices yet.

**Comment by taojiastanford** [comment]
Dear Dr. Gambetta,
Thank you for your reply!
I was using the composer linked to ibmqx2, but this error also disables  "simulate".
Sincerely,
Tao Jia

----------
Tao Jia
PhD Candidate
Stanford University
Tel: 6503871627

**Comment by rraymondhp** [comment]
@jaygambetta 
Is the following control-if supported in the real device? I have been using it with the simulator:
```
queryStateCircuit.x(qr[N]).c_if(cr, 0)
queryStateCircuit.h(qr[N]).c_if(cr, 0)
```

**Comment by jaygambetta** [comment]
@rraymondhp all the qasm simulators should support this.

**Comment by taojiastanford** [comment]
I also found that I could not create multiple classical registers. The following code:

> include "qelib1.inc";
qreg q[5];
creg c0[1];
creg c1[1];
h q[0];
t q[0];
h q[0];
cx q[0],q[1];
h q[0];
measure q[0] -> c0[0];
measure q[1] -> c1[0];

This does not have compile error, but when I tried to simulate it I found "Generic error".
Am I supposed to only use one classical register?

**Comment by rraymondhp** [comment]
Hello @taojiastanford 
Sorry for the late response. 

I confirmed that the code can be compiled and can run with the simulators. I believe you got the error message because you executed the qasm code (with QASM editor instead of the QISKit tutorial) using the topology of the real device on IBM Q experience, right? Is it correct? 

If so, the error (bug) is due to the limitation of commands used to operate the real device. You are right that at the moment one is supposed to use one type of classical register.  The error message should report this clearer instead of "Generic Error" message. 

Thank you very much for reporting this.

**Comment by rraymondhp** [comment]
Hi Tao,
Thanks for your contribution. We really appreciate it.  Please just call me Raymond.

Meanwhile, about your questions, the real devices `ibmqx2` and `ibmqx3` has connectivity limitations: not all circuits that can be run on real devices, even though they can be run on simulators.   For example, if you use real devices, a measurement will end the execution of your program. In this case, the teleportation code, as you gave me, cannot run the classically controlled gates. 

For the number of shots, at the moment, there is an upper limit for one submission, but I think you can trivially combine two submissions with N1 shots and N2 shots, and essentially get N1 + N2 shots of experiments, and so on. 

About the error for the experiment, I believe this is a bug report to be handled by IBM Q experience (the web interface). I will forward your suggestion to the forum here: 
https://quantumexperience.ng.bluemix.net/qx/community

There is a tutorial on quantum teleportation here, that allows you to write the program with python interface:
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/2_quantum_information/quantum_teleportation.ipynb

**Comment by jaygambetta** [comment]
@taojiastanford and @rraymondhp I think this issue is solved. I will close the thread but please open it again if there is more. 

For the bug can you use the bug tracker on the IBM Q experience website. 

Thanks

**Comment by KishoreSShenoy** [comment]
@rraymondhp the link you shared does not work now. Can you send another one, or share the code?

**Comment by muneerqu** [comment]
Hi @KishoreSShenoy 

Please try these links [Teleportation](https://github.com/Qiskit/qiskit-tutorials/blob/31ea17ed50f8af83b6c3fa31c10a3ea326d03f8b/community/terra/qis_intro/teleportation_superdensecoding.ipynb) / [nbviewer-Teleportation](https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/31ea17ed50f8af83b6c3fa31c10a3ea326d03f8b/community/terra/qis_intro/teleportation_superdensecoding.ipynb)
