### ISSUE TITLE
Explain the concept of equivalence up to global phase

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-tutorial#191]
The `initialize()` in the tutorial does not produce the exact state as desired vector, but it only gives one that is equivalence up to global phase. 
https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/reference/tools/quantum_gates_and_linear_algebra.ipynb#Arbitrary-initialization

## Description

I think it is good to mention about the equivalence up to global phase here also (in addition to a single qubit case mentioned before). 

## Your Environment

* QISKit version: 0.5.3
* Python version: 3.6.x

**Comment by jaygambetta** [comment]
@rraymondhp make a pr and suggest how you want to do it.

**Comment by jaygambetta** [comment]
I am closing this but if you do come up with something that you think better describes global phase make a pr.
