### ISSUE TITLE
symbolic link to qiskit tools not working under Windows

### ISSUE THREAD

**Issue by alfrisch** [QISKit/qiskit-tutorial#20]
## Expected Behavior
A symbolic link is in place in qiskit-sdk-py after moving tools into the folder qiskit.

## Current Behavior
When checking out qiskit-sdk-py under Windows the symbolic link is being converted into a textfile. Hence I get a NotFoundError when loading any tools.

## Possible Solution
Add "qiskit." to tools import statements. 

## Steps to Reproduce (for bugs)
1. checkout qiskit-sdk-py under Windows
2. try running Jupyter notebooks that are importing tools from qiskit-sdk-py

## Your Environment
* Operating System and version: Windows 7

**Comment by alfrisch** [comment]
I have prepared a pull request for fixing the NotFoundError, see pull request #21

**Comment by alfrisch** [comment]
I also submitted a pull request in qiskit-sdk-py and double checked all occurences of tools imports.
After merging that request I suggest to remove the symbolic link.

**Comment by jaygambetta** [comment]
I know but lets talk in that. I think i want you to push it to r0.3 and we need to update pip.

Thanks

**Comment by alfrisch** [comment]
updates are pushed to r0.3, closing this issue
