### ISSUE TITLE
Error during measurement quantum register in loop.. Gates are blocked

### ISSUE THREAD

**Issue by amandeep1988** [Qiskit/qiskit-tutorial#232]
Dear Sir,

I am trying to measure quantum register in loop. And, it will try to access backend again n again while in loop. My question is : is it possible to measure quantum register in loop only after getting access backend at once. Otherwise, after one measurement it displays: gates are blocked...error...

Please give solution or any tutorial handling it..

Status @ 20 seconds
{'job_id': None, 'status': <JobStatus.ERROR: 'job incurred error'>, 'status_msg': "{'status': 400, 'message': 'Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked', 'code': 'QASM_NOT_VALID', 'statusCode': 400}"}
Status @ 25 seconds
{'job_id': None, 'status': <JobStatus.ERROR: 'job incurred error'>, 'status_msg': "{'status': 400, 'message': 'Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked', 'code': 'QASM_NOT_VALID', 'statusCode': 400}"}

## Your Environment

* QISKit version:
* Python version:

**Comment by rraymondhp** [comment]
Hi,

Please tell us the QISKit version and Python version.
Also, posting your code, if possible, will be helpful.

**Comment by amandeep1988** [comment]
Python 3.6.5
QISkit 0.5.6.

**Comment by amandeep1988** [comment]
from qiskit import QuantumProgram

data =set[:100,:10]
labels=set[:100,10]-1

qp=QuantumProgram()
no_qubits=4
qr = qp.create_quantum_register('qr',no_qubits)
cr = qp.create_classical_register('cr', 1)
qc = qp.create_circuit('test', [qr], [cr])
p=initialise_params(7)
one_time=np.zeros(len(labels))

def evaluate_cost(data, labels, p):
    for k in range(len(lables)):
        for j in range(data.shape[1]):
            qc.ry((2*data[k,j]),qr[j])
        print(k)
        for j in range(no_qubits):
            qc.ry(p[j],qr[j])

        qc.cx(qr[0],qr[1])
        qc.cx(qr[3],qr[2])
        qc.ry(p[no_qubits],qr[1])
        qc.ry(p[no_qubits+1],qr[2])
        qc.cx(qr[1],qr[2])
        qc.ry(p[no_qubits+2],qr[2])
        qc.measure(qr[2],cr[0])
        print(k+1)
        job_exp = qp.execute('test',backend=backend, shots=1024, max_credits=3)  
        lapse = 0
        interval = 5
        while not job_exp.done:
            print('Status @ {} seconds'.format(interval * lapse))
            print(job_exp.status)
            time.sleep(interval)
            lapse += 1
        print(job_exp.status)
        
        sim_result = job_exp.result()
        print(job_exp.get_counts(qc))
        prob_zero=job_exp[0]['data']['counts']['0']/(job_exp[0]['data']['counts']['1']+job_exp[0]['data']['counts']['0'])
        one_time[k]=abs((1-prob_zero)-labels[k])
        print(k+3)
        if one_time[k]<0:
            print('no')
            print(prob_zero)
            print(labels[k])
        print(one_time[k])
    total_amount=np.sum(one_time)/len(one_time)
    print(total_amount)
    return total_amount
 
total_amount=evaluate_cost(data, labels, p)
print(total_amount)

**Comment by amandeep1988** [comment]
After executing it ...it displays as (I got output at once, when it tries to get backend in loop then displays Gates are blocked... 

I need to calculate total_amount till the loop fails..

{'job_id': '5b5558175dc974003b7afabe', 'status': <JobStatus.DONE: 'job has successfully run'>, 'status_msg': 'job has successfully run'}
{'0': 530, '1': 494}
0.482421875
Status @ 0 seconds
{'job_id': None, 'status': <JobStatus.INITIALIZING: 'job is being initialized'>, 'status_msg': 'Job is initializing. Please, wait a moment.'}
Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID","statusCode":400}}
Status @ 5 seconds
{'job_id': None, 'status': <JobStatus.INITIALIZING: 'job is being initialized'>, 'status_msg': 'Job is initializing. Please, wait a moment.'}
Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=: {"error":{"status":400,"message":"Error parsing QASM. Error parsing qasm number 0. Gates after a measure are blocked","code":"QASM_NOT_VALID","statusCode":400}}

**Comment by rraymondhp** [comment]
Hi,
Thanks for posting the code. Still the code is not clear and I cannot repeat the experiment.

1. We do not use `QuantumProgram` anymore since qiskit version 0.5. Instead, we can create `QuantumCircuit`s and execute them directly.

2. I do not see you import `Qconfig` and register your APItoken to use the remote backends. What is the backend you used in the above?

**Comment by amandeep1988** [comment]
can you please give a link of some tutorial regarding creating quantum
circuit ..anythng

**Comment by rraymondhp** [comment]
Here you go:
https://github.com/Qiskit/qiskit-tutorial/blob/8e1cc40fce8d30113cef0a663d80d39b2f364dbd/hello_world/quantum_world.ipynb

**Comment by attp** [comment]
Hi @amandeep1988 , I'm not sure what you are trying to do from your code, but on the IBM QX devices, we currently lack the ability to use measurement feedback or feed forward. So once there is a measurement in a circuit, you can't implement any further gates. See https://github.com/Qiskit/qiskit-tutorial/blob/master/reference/algorithms/iterative_phase_estimation_algorithm.ipynb for an example of how to work around this restriction.

**Comment by jaygambetta** [comment]
I think @attp answer is correct @amandeep1988 please reopen if you still have problems.
