### ISSUE TITLE
Question about circuit_drawer

### ISSUE THREAD

**Issue by kwyip** [Qiskit/qiskit-tutorial#241]
## Description

In the example script below, when circuit_drawer is called, does the image pop up? I just get stuck there and does not see any circuit image. If this is just my problem, is there anyway to save the image instead?
## Your Environment

* QISKit version: latest
* Python version: 3.6

Example script:
```
# importing QISKit# impor 
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, QISKitError
from qiskit import available_backends, execute, register, get_backend, compile

from qiskit.tools import visualization
from qiskit.tools.visualization import circuit_drawer

q = QuantumRegister(6)
qc = QuantumCircuit(q)
qc.x(q[2])
qc.x(q[2])
circuit_drawer(qc)
```

**Comment by rraymondhp** [comment]
Hi,

I am using macOSX. Replacing the last line with the following line gave me a pop-up image of the circuit:
```
circuit_drawer(qc).show()
```

**Comment by kwyip** [comment]
It does not seem to work for me. I cannot find the source code of circuit_drawer or qiskit.tools.visualization, so I can try to see how to save the image. Do you know where I can find it?

**Comment by rraymondhp** [comment]
If you can use jupyter notebook, I suggest you plot the circuits like this tutorial:

https://nbviewer.jupyter.org/github/QISKit/qiskit-tutorial/blob/master/reference/tools/matplotlib_circuit_drawer.ipynb

**Comment by rraymondhp** [comment]
I think this issue has been solved. Please reopen it if the problem persists.
