### ISSUE TITLE
Incomplete installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by ntwalibas** [Qiskit/qiskit-tutorial#244]
## Description
Libraries cvxopt, mkl-random, mkl-fft and twisted would not install.

From what I could tell, this may be due to changes upstream and have nothing to do with Qiskit.  
Though I solved this issue for myself, it would be nice if the installation went without any problems, especially for those not used to the Python ecosystem.

### Installation directions
Even in the case of an incomplete installation, you will still have an environment created which will allow you to run the commands below.  
First, activate your conda environment with.
```
source activate QISKitenv
```
That ensure that any subsequent installations target that environment. 

- **Installing cvxopt:**
This one failed because GCC couldn't compile UMFPACK.  
```
conda install -c conda-forge cvxopt
```
That will install the latest version of cvxopt which I assume is what is desired since the original spec file from Qiskit doesn't seem to specify versions for anything other than Python.

- **Install mkl-random and mkl-fft**
Those two failed because I was missing Cython.  
So you need to install Cython to solve the problem, if that is your case as well.  
```
conda install -c anaconda cython
```
After a successful Cython installation, update your installation.
It is good to do this since 1) it won't reinstall packages from scratch but will check installed ones against whatever version is newest, 2) you get to know about packages that could not be installed.
```
conda env update -f QISKitenv.yml
```

- **Install twisted**
This package was missing because another package (automat) had the incorrect version installed.  
So if that is your case, just update `automat`. If the package is missing, it should be installed for you, else install it yourself.  
```
conda update -c anaconda automat
```
Of course, perform another update of your conda environment to be sure that all packages are installed properly.  
If all goes well, there will be no errors in red and you will be asked to activate your environment.

## My Environment
* QISKit version: 0.5.7
* Python version: 3.6.6
* Conda: 4.5.4
* OS: Ubuntu 16.04.5 LTS

**Comment by jaygambetta** [comment]
@ntwalibas with @rraymondhp fix this should be working. If not please open again. 

Thanks @rraymondhp
