### ISSUE TITLE
How can i get the job results if I lost connection when jobs are on queue?

### ISSUE THREAD

**Issue by kwyip** [Qiskit/qiskit-tutorial#249]
## Your Environment

* QISKit version: latest
* Python version: 3.6

I submitted the job. Then the job is on queue, with its jobID shown. Since this takes some time especially when the queue position is high, I need to close my computer (internet connection also lost). When I open my computer again, I can no longer get access to that job again.
The status changes from `JobStatus.QUEUED: 'job is queued'`to `JobStatus.ERROR: 'job incurred error'`. How can I keep the job on the queue? or how can obtain the execution result since I have the jobID?

**Comment by kwyip** [comment]
After some testings and with the help of [this snippet](https://github.com/t-imamichi/qiskit-utility/blob/master/run_qasm.py), I confirmed that the job will continue to run and I can also retrieve the result.
However, if there is a disconnection when the job is on queue, in the original terminal where you run the program, it will just get stuck as `JobStatus.ERROR: 'job incurred error'`forever after the it is connected to the internet again. So I cannot do any saving/postprocessing of data. Is there any solution to this? So it seems that the only way to retreive the data is to use the above snippet.

**Comment by ewinston** [comment]
You can still retrieve the jobs which have been queued after you close your python session. To do this you would just create an instance of your backend and call `mybackend.jobs()`. This will return a list of `job` instances from which you can retrieve your results. The `jobs` function can be supplied several options you can use to filter what jobs you get back,

https://qiskit.org/documentation/_autodoc/qiskit.backends.ibmq.ibmqbackend.html#qiskit.backends.ibmq.ibmqbackend.IBMQBackend.jobs

**Comment by jaygambetta** [comment]
@ewinston answer should fix this. Closing the issue and if you have problems please reopen
