### ISSUE TITLE
Stuck with my QISkit Installation, Please help! 

### ISSUE THREAD

**Issue by a07r** [Qiskit/qiskit-tutorial#254]
Couldn't locate a solution to my problem on the wiki link provided above

## Description

I ran " conda env create -f QISKitenv.yml " just as the guide asked me to do so, and I get following error - 

Failed building wheel for psutil
  Running setup.py clean for psutil
  Running setup.py bdist_wheel for mpmath ... done
  Stored in directory: /home/aman/.cache/pip/wheels/33/15/0f/9ca5f2ad88a5456803098daa189f382408a81556aa209e97ff
Successfully built sympy IBMQuantumExperience mpmath
Failed to build psutil
qiskit-acqua 0.1.2 has requirement numpy<1.15,>=1.13, but you'll have numpy 1.15.1 which is incompatible.
qiskit-acqua-chemistry 0.1.1 has requirement numpy<1.15,>=1.13, but you'll have numpy 1.15.1 which is incompatible.

----------------------------------------
Command "/home/aman/anaconda3/envs/QISKitenv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wamejjyg/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ztpm9ns3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wamejjyg/psutil/

CondaValueError: pip returned an error

## Your Environment

* QISKit version: still trying to install 
* Python version: My Conda has 3.7  
* Conda Version: current version: 4.5.4

**Comment by a07r** [comment]
@rraymondhp 
Can you help me see this error off please!

**Comment by rraymondhp** [comment]
@a07r  Sorry for the late response.
It seems that you do not have psutil installed in your system and failed to compile it from the source.

Would you please try installing psutil following the link below? 
https://github.com/giampaolo/psutil/blob/master/INSTALL.rst

**Comment by a07r** [comment]
@rraymondhp  I tried that, error is still the same as above even after installing psutil 

I used " conda install -c anaconda psutil " to install it and it ran successfully. 

there's another line that says error, perhaps that can help you get a clue, 

Running setup.py bdist_wheel for psutil ... error

----------------------------------------
  
  Running setup.py install for psutil ... error

Maybe my setup.py is not right, I just can't locate it to go see what's inside it?

**Comment by rraymondhp** [comment]
Hi,
Do you still have this problem? If not I recalled that someone proposed to fix the version of each package used by qiskit for smooth installation. The instruction is here: 
https://github.com/Qiskit/qiskit-tutorial/wiki/FAQ-and-Troubleshootings

Please let me know if you the above works. If not, I will look for other way around.

**Comment by a07r** [comment]
I have reported this issue in slack channel [ #qiskit-community ] 

Robert Loredo, pointed out - "qiskit-acqua 0.1.2 has requirement numpy<1.15,>=1.13, but you'll have numpy 1.15.1 which is incompatible." could be a cause. and hence I went ahead and got the numpy downgraded to 1.14.5 from 1.15.1 and pip list and conda list confirms that i have numpy 1.14.5 running on my conda, it's just that when I run "conda env update -f QISKitenv.yml" it somehow still finds numpy 1.15.1

**Comment by muneerqu** [comment]
Hi a07r,

I think everytime you run `conda env update -f QISKitenv.yml` you install the newest numpy (numpy=1.15) even if you have downgraded it before in the same env. To force installing numpy=1.13 try the following:
1. Open `qiskit-tutorial/QISKitenv.yml`
2. Under dependencies add `numpy=1.13`
3. In the current tutorial `QISKitenv.yml` will looks like:
```
name: QISKitenv
dependencies:
- python=3
- pip
- notebook
- scipy
- cvxopt
- scikit-learn
- cython
- matplotlib
- sympy
- pillow
- numpy=1.13
- pip:
  - qiskit
  - qiskit-aqua
  - qiskit-aqua-chemistry
```
4. Run `conda env update -f QISKitenv.yml`

Let me know if the above steps works and/or if you face other errors

**Comment by a07r** [comment]
Hi Muneer,

Somehow I had lot of dependencies missing on my machine, I had to install them one after the other and was successful in doing so. but for some reason they never showed up on my QISKitenv.yml file not sure if that's a hard requirement (you can see my yml file in this issue). Not knowing if I have to manually add them in the yml file I went ahead and followed the steps that you have shared in your Youtube video i.e. reinstalling afresh by hard coding numpy to be 1.13 in the yml file. and I now have following error - 

building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    gcc -pthread -B /home/aman/anaconda3/envs/QISKitenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=547 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/aman/anaconda3/envs/QISKitenv/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/aman/anaconda3/envs/QISKitenv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lic8i0q1/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-nmx6eio1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-lic8i0q1/psutil/

CondaValueError: pip returned an error

[aman@oc7415214385 qiskit-tutorial]$

@muneerqu

**Comment by rraymondhp** [comment]
@a07r  
Hi, I wonder if you have switched to the `QISKitenv` before updating and installing with `pip`. You have to do `source activate QISKitenv` before installing and/or upgrading in the environment. Otherwise the updates and installs are not properly done at the intended environment. 

Please refer to this for conda env:
https://conda.io/docs/user-guide/tasks/manage-environments.html

**Comment by a07r** [comment]
Hi,
It's doing all it's doing after I ran " conda env create -f QISKitenv.yml " and get above error.. I don't know why it's trying to update and install using pip on it's own.
Am I missing anything here?

**Comment by rraymondhp** [comment]
It seems that you do not have `gcc` installed. Depends on your Linux distribution, but you have to install the gcc package first. 

```
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
```

**Comment by a07r** [comment]
Hi Again, That solved the problem. It isn't throwing me any error anymore. 
Thanks a lot!

**Comment by muneerqu** [comment]
Great,
This command installs gcc on Red Hat and CentOS:
` yum groupinstall 'Development Tools' `

**Comment by a07r** [comment]
@muneerqu I have directly installed gcc alone using yum.. What do you reckon? Shall I run above yum command or not?

**Comment by muneerqu** [comment]
If everything works fine, don't install it. Just keep it as a reference for the future.

**Comment by rraymondhp** [comment]
Great.. I can close this issue.
