### ISSUE TITLE
can't pip install qiskit

### ISSUE THREAD

**Issue by andysc** [Qiskit/qiskit-tutorial#256]
## Description
Trying to install qiskit from instructions here: `qiskit-tutorial/INSTALL.md`

```
pip install qiskit
Collecting qiskit
  Could not find a version that satisfies the requirement qiskit (from versions: )
No matching distribution found for qiskit
```

## Your Environment

* QISKit version: latest
* Python version: 2.7.10
* MacOS

**Comment by t-imamichi** [comment]
Qiskit requires Python 3.5 or later. See https://github.com/Qiskit/qiskit-terra#dependencies

**Comment by quantumjim** [comment]
Good catch. We need dependency info in the the INSTALL.md. I added some in a new PR: https://github.com/Qiskit/qiskit-tutorial/pull/257

**Comment by andysc** [comment]
that would be helpful to mention :)
Also, worth explaining how you make the commands work when you ALSO have python 2.7 installed, please.

**Comment by quantumjim** [comment]
I changed some things around in the guide to help those that run into problems: PR [#260](https://github.com/Qiskit/qiskit-tutorial/pull/260)

**Comment by jaygambetta** [comment]
Closing if there are still issues please reopen. Thanks @quantumjim for the fix.
