### ISSUE TITLE
Community - terra

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorial#285]
## Description

I would like to have some thinking about how we arrange community terra. It should have some structure inside so that the awesome inputs from the community are useful for people wanting to learn about quantum information science using qiskit. 

We have many great tutorials and there needs a great path off learning. 

The landing from the main file is 
3.4 Quantum Information Science with Qiskit Terra
Learn about and how to program quantum circuits using Qiskit Terra. 

## Your Environment

* QISKit version:
* Python version:

**Comment by jaygambetta** [comment]
@attp can you think about this.

**Comment by muneerqu** [comment]
I am going to reference some updates on some tutorials in [community/terra](https://github.com/Qiskit/qiskit-tutorial/tree/master/community/terra) to run on Qiskit 0.6.1. 
I would appreciate any feedback.

**Comment by jaygambetta** [comment]
I’m not sure I know what you mean.

**Comment by muneerqu** [comment]
I updated some notebooks and I am wondering if I should create a PR or reference the changes here for review/feedback before I create the PR.

**Comment by jaygambetta** [comment]
Making a PR would be great.

**Comment by attp** [comment]
Initial plan to have a set of introductory notebooks introducing superposition & entanglement: 
    Single Qubits: Superposition
    Single Qubits: Amplitude and Phase
    Multiple Qubits: Creating Entanglement
    Multiple Qubits: Testing Entanglement
    Multiple Qubits: Teleportation and Superdense Coding

**Comment by quantumjim** [comment]
The introductory set of notebooks sound good. Maybe some of the proposed topics could be combined (like a single notebook for creating and testing entanglement), but such things probably only become clear in the writing.

I wonder if it might be possible to include little code challenges in these. Where we leave a code block for people to add in some qiskit code, with the aim of creating some specified set of results.

For the time being, I see no reason to split qec out from qis_adv (unless we are happy with a folder that currently only has one thing in). But being a rather qec focused person, I agree that there should be more content on this topic and that it should get its own folder when that comes.

**Comment by quantumjim** [comment]
I had not noticed that the intro notebooks mentioned by @attp are ones that already exist. So some of what I said above is nonsense, but it still might be nice to see if more exercises could be fitted into them somehow.

**Comment by jaygambetta** [comment]
I like the introductory ones and think the folder is good. I don’t like what I wrote in amplitude and phase and I would make it more like the user guide i updated. Have you looked at that

**Comment by attp** [comment]
Thanks for your input @quantumjim and @jaygambetta, I'll:
1. set up the structure with qis-intro, qis-adv, qec. I like the idea of having a folder with one tutorial, and asking for contributions.  
2. rework the introductory tutorials to be more accessible (I'll have a look at the QX user guide as well) and add exercises (great idea!), 
3. update the advanced ones for qiskit 0.6 (I see that @muneerqu is doing some of these as well).

**Comment by jaygambetta** [comment]
Sounds great.

**Comment by jaygambetta** [comment]
@attp I think we can close this and you can make a new one to change it. Do you agree.

**Comment by attp** [comment]
yes, I agree, the initial rearranging is complete.
