### ISSUE TITLE
Community - teach me qiskit 2018

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorial#306]
## Description

There are 3 notebooks that fail to open. @rraymondhp could you look into why

- [ ] qiskit-tutorial/community/teach_me_qiskit_2018/state_distribution_in_qubit_chains/qubit_chain.ipynb 

- [ ] qiskit-tutorial/community/teach_me_qiskit_2018/state_distribution_in_qubit_chains/qubit_chain_mod.ipynb 

- [ ] qiskit-tutorial/community/teach_me_qiskit_2018/state_distribution_in_qubit_chains/qubit_chain_mod_many.ipynb 

## Your Environment

* QISKit version:
* Python version:

**Comment by qubeat** [comment]
Hello. Updated version of all my notebooks is still here https://github.com/qubeat/quchain/tree/qiskit_fix/IBM-QE/qiskit-simulator 
three days ago I tested three notebooks you mentioned with Qiskit 0.6.1. It worked.

**Comment by jaygambetta** [comment]
@qubeat is it possible that you can contribute them to the folder here or work out with @rraymondhp how to link to that repo

**Comment by qubeat** [comment]
@jaygambetta it is up to you and @rraymondhp  I just mean, my notebooks for Qiskit-0.6 are ready and may be used instead of earlier version. Should I do a pull request or wait some time?

**Comment by muneerqu** [comment]
@qubeat can you make sure the `Quantum Sphere` mode works in `qubit_chain_mod.ipynb`? I get `KeyError: 'quantum_state'` when I set:
```python
# Quantum Sphere
hist = False
```
let me know if i'm missing something.

**Comment by jaygambetta** [comment]
@qubeat I would prefer you to do the Pr that way we get your original contributions added. I would also add to the readme in the teach_me_qiskit_2018 folder a note like @qubeat made this version of the tutorial 0.6 compatible under the link to your tutorial.

**Comment by qubeat** [comment]
@muneerqu  I just checked, the `hidden option` indeed does not work more. I also reread newer documentation and tried to use 'statevector' instead of 'quantum_state', but it does not work either. Maybe I missed something. Maybe trick with shot=1 does not work more and I should delete the commented option and `hist'.

**Comment by qubeat** [comment]
@muneerqu I fixed the notebook. The hist = False option should work now and draw quantum sphere

**Comment by muneerqu** [comment]
@qubeat Yes, it works.

**Comment by jaygambetta** [comment]
Don’t use the shots equals one. Use the state vector backend. 

Good point about the raw text I should change the file from readme.ipynb to index.ipynb or something.

**Comment by jaygambetta** [comment]
Yeah but the readme.md could not link from the master ipynb. I see now that github does not render readme.ipynb which is strange. I don’t want to have two files that have same content so I make a new name.

**Comment by jaygambetta** [comment]
I changed it to index.ipynb and now it does not display which I think is better but you need to click on it. 

When you do you pr iI would take the line form 

https://github.com/Qiskit/qiskit-tutorial/blob/258c5c1ec725f981ab366fcfc26ef60090ba7b72/community/teach_me_qiskit_2018/index.ipynb

and add it to the qiskit 0.6 section. 

Hope that helps.

**Comment by qubeat** [comment]
@jaygambetta I created the pull request
