### ISSUE TITLE
pip install qiskit does not install ipywidgets

### ISSUE THREAD

**Issue by attp** [Qiskit/qiskit-tutorial#314]
## Description
`pip install qiskit` does not install ipywidgets and thus causes an error in `getting_started.ipynb`

## Your Environment
* QISKit version: 0.6.1
* Python version: 3.6.5

**Comment by nonhermitian** [comment]
ipywidgets, and Juypter itself, are not required to run qiskit, and are therefore not installed by the pip installer.  All of the stuff needed to run the notebooks is in the `environment.yml` file in the tutorials directory, and we give instructions on how to install it.  That being said, all of the stuff you need to run the notebooks is included by default in the Anacona Python distrobution, and has been for a couple of years now.

**Comment by attp** [comment]
Thanks, I'm using qiskit through an Anaconda environment and it wasn't installed automatically, so this might be a problem that others run into (I saw the same question on the slack community as well).

**Comment by nonhermitian** [comment]
I would think the best solution is to spell out the requirements somewhere in the readme or install instructions. Right now everything needed is in the environment.yml, but not really explicitly spelled out. 

Another option would be to have the environment installed by qiskit install everything needed for the tutorials as well, even though some things are not strictly necessary for qiskit itself. I kind of like this latter option.

**Comment by jaygambetta** [comment]
did you run 

```
conda env create -f environment.yml
```

**Comment by attp** [comment]
Ah, no I didn't upgrade my environment as the install instructions suggest. Thanks.
