### ISSUE TITLE
aqua classical_optimization tutorial using real quantum computer

### ISSUE THREAD

**Issue by zzhan127** [Qiskit/qiskit-tutorial#342]
## Description

I am working on the classical_optimization in aqua directory. It works well using qasm_simulator. However, when changing params['backend']['name'] = 'qasm_simulator' to params['backend']['name'] = 'ibmqx4' or params['backend']['name'] = 'ibmq_16_melbourne', the code runs endlessly and starts creating jobs on the quantum computer again and again. Then, when I check the histogram results of jobs, it seems that I cannot find the right solution according to the simulation because the probability of each output are similar. Did I make any mistake during the process?

## Your Environment

* QISKit version: qiskit 0.6 aqua 0.3 
* Python version: 3.7

Thanks a lot!

**Comment by zzhan127** [comment]
![screenshot from 2018-10-15 22-31-00](https://user-images.githubusercontent.com/25940833/46989679-f6a8db80-d0cb-11e8-8e12-b3b3c2a5db0c.png)
The left is the plot of real ibmqx4 result and the right one is the qasm_simulator result.

**Comment by chunfuchen** [comment]
There are a couple of things:
1. VQE underlying creates the circuits for each iteration, so you will see the multiple job creation.
2. The results on the simulator and real hardware could be different since the tutorials run the example on a noise-free simulation. You might need to apply some technique to mitigate those errors when you experimenting on a real device.

**Comment by zzhan127** [comment]
> There are a couple of things:
> 
> 1. VQE underlying creates the circuits for each iteration, so you will see the multiple job creation.
> 2. The results on the simulator and real hardware could be different since the tutorials run the example on a noise-free simulation. You might need to apply some technique to mitigate those errors when you experimenting on a real device.

Thanks. I will investigate more on how to mitigate the errors in real device. 

But when I run this part using  'ibmq_16_melbourne' in jupyter,  
`# run quantum algorithm with shots
params['algorithm']['operator_mode'] = 'grouped_paulis'
params['backend']['name'] = 'ibmq_16_melbourne'
params['backend']['shots'] = 4086

result = run_algorithm(params, algo_input)
x = maxcut.sample_most_likely(result['eigvecs'][0])
print('energy:', result['energy'])
print('time:', result['eval_time'])
print('maxcut objective:', result['energy'] + offset)
print('solution:', maxcut.get_graph_solution(x))
print('solution objective:', maxcut.maxcut_value(x, w))
plot_histogram(result['eigvecs'][0])

colors = ['r' if maxcut.get_graph_solution(x)[i] == 0 else 'b' for i in range(n)]
nx.draw_networkx(G, node_color=colors, node_size=600, alpha = .8, pos=pos)`
It runs endlessly and I cannot get final results after running a whole night, do you know what happens here?

**Comment by chunfuchen** [comment]
I think it is because your job is queued for a long time.
You can turn on the aqua logging to see the progress of optimization.

like 
```
import logging
from qiskit_aqua._logging import set_logging_config, build_logging_config
set_logging_config(build_logging_config(logging.INFO))
```
