### ISSUE TITLE
Is it meaningful to test the speed of algorithms running on local simulator?

### ISSUE THREAD

**Issue by yangjy0826** [Qiskit/qiskit-tutorial#346]
## Description

Hi, I am new to the quantum computing area, and I am now studying some quantum algorithms. I would like to compare the speed of quantum algorithm and traditional algorithm using QISKit, like QFT and FFT. 

I find that the remote chips are usually busy, so the running time is quite long and I deciede to use local simulator instead. But I am not sure if it is meaningful to test the speed on a local simulator, because in my opinion, the simulator is lack of many advantages of quantum computers.

Could you please give me some advice on how to do this kind of comparision? Thank you.

## Your Environment

* QISKit version: 0.6.0
* Python version: 3.6

**Comment by ajavadia** [comment]
Hi @yangjy0826. If you're just interested in how long the program takes to execute on a quantum computer, you can probably make some estimates based on the circuit depth. You don't actually need to run anything. Just take the circuit, compile it, and then add up the delays on the longest path of the compiled circuit. Single qubit gates are (ballpark) 10 ns, and two qubit gates 100 ns.

Simulation on classical hardware does not follow this pattern (it comes down to multiplying matrices on your laptop). Also even if you could run your program on a quantum computer (as you can, just have to wait a bit in queue), the execution time you get is a combination of actual runtime plus overhead of loading waveforms, etc. onto the device (the classical control). I suppose you just want the actual gate delays, so my suggestion above is probably the best bet.
