### ISSUE TITLE
Example of classical control needed for multi-bit registers

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-tutorial#356]
## Description
The notebook on ['using different gates'](https://github.com/Qiskit/qiskit-tutorial/blob/master/qiskit/terra/using_different_gates.ipynb) has an example of classical control for a single bit register. It is not trivial to work out how to adapt this for a many bit register, so an additional example should be given.

This can then be used to answer [this question](https://quantumcomputing.stackexchange.com/questions/4260/how-to-create-a-condition-on-only-one-classical-bit-when-we-have-a-total-of-2-cl) on the QCSE.

## Your Environment

* QISKit version:
* Python version:

**Comment by quantumjim** [comment]
I posted [this answer](https://quantumcomputing.stackexchange.com/a/4516/409) to the above question. It seems a bit of a hack to me, but if it represents best practice then I'll add it to the tutorial.

**Comment by rraymondhp** [comment]
I have written a small example here using `c_if` (is it what you mean by classical control?) 
https://github.com/Qiskit/qiskit-tutorial/blob/master/community/games/quantum_counterfeit_coin_problem.ipynb

```
# we proceed to query the quantum beam balance if the value of cr[0]...cr[N] is all zero
# by preparing the Hadamard state of |1>, i.e., |0> - |1> at qr[N]
queryStateCircuit.x(qr[N]).c_if(cr, 0)
queryStateCircuit.h(qr[N]).c_if(cr, 0)

# we rewind the computation when cr[N] is not zero
for i in range(N):
    queryStateCircuit.h(qr[i]).c_if(cr, 2**N)

```

**Comment by quantumjim** [comment]
@rraymondhp As I understand, the first two examples here are conditioned on an entire classical register being zero, and the third is conditioned on the register being `100...000`. Is this correct? What I'm specifically asking is how to use  a `c_if` command that is conditioned on just a single bit.

@jaygambetta I opened [this issue](https://github.com/Qiskit/qiskit-terra/issues/1160).

**Comment by rraymondhp** [comment]
@quantumjim  Yes, you are correct. I was not able to write individual bit as a controller, and hence that style of writing. This is because the `c_if` only accept argument the whole classical bit.

**Comment by jaygambetta** [comment]
great lets close here and track in terra
