### ISSUE TITLE
How to run Qisqit using Google colab notebooks

### ISSUE THREAD

**Issue by ModMaamari** [Qiskit/qiskit-tutorial#359]
## Description
The line : 
`!source activate Qiskitenv`
is not working in colab.research.google.com notebooks
the error message I'm facing is :
`/bin/bash: activate: No such file or directory`
## My Environment
colab.research.google.com notebook with GPU on, and Python 3.6.6
* Python version: Python 3.6.6

**Comment by muneerqu** [comment]
You just need to run this code in a Google colab notebook to install Qiskit.
```
!pip install qiskit ipywidgets
```

**Comment by jaygambetta** [comment]
@muneerqu and @ModMaamari is there still an issue here or can we close this. 

@muneerqu thanks for the fix

**Comment by muneerqu** [comment]
@jaygambetta You can close this issue. I will be happy to help @ModMaamari if more help is needed.
