### ISSUE TITLE
terra/compiling_and_running notebook is still using qiskit 0.5 conventions (e.g. QuantumProgram)

### ISSUE THREAD

**Issue by dtmcclure** [Qiskit/qiskit-tutorial#370]
## Description
It was pointed out to me that the notebook at https://github.com/Qiskit/qiskit-tutorial/blob/master/qiskit/terra/compiling_and_running.ipynb is trying to import QuantumProgram despite being in the section of notebooks that should be kept up to date for the latest Qiskit version. This is generating an error.

## Your Environment

* QISKit version: 0.6
* Python version: 3.6

**Comment by jaygambetta** [comment]
This is not updated and will be removed it was moved due to a mistake
