### ISSUE TITLE
AttributeError: module 'qiskit' has no attribute 'unroll'

### ISSUE THREAD

**Issue by dhruvmalik007** [QISKit/qiskit-tutorial#4]
when i try to import the library
`from qiskit import QuantumProgram`
`qp = QuantumProgram()`

i get pesky error

` AttributeError                            Traceback (most recent call last)
<ipython-input-13-0092c73e2d1c> in <module>()
----> 1 from qiskit import QuantumProgram
      2 qp = QuantumProgram()

~/qiskit-sdk-py/qiskit/__init__.py in <module>()
      8 from ._qiskitexception import QISKitException
      9 import qiskit.extensions.standard
---> 10 from ._quantumprogram import QuantumProgram

~/qiskit-sdk-py/qiskit/_quantumprogram.py in <module>()
     39 from . import unroll
     40 from . import qasm
---> 41 from . import mapper
     42 
     43 # Local Simulator Modules

~/qiskit-sdk-py/qiskit/mapper/__init__.py in <module>()
      1 from ._coupling import Coupling
----> 2 from ._mapping import swap_mapper, direction_mapper, cx_cancellation, optimize_1q_gates

~/qiskit-sdk-py/qiskit/mapper/_mapping.py in <module>()
     28 from qiskit import QISKitException
     29 from qiskit.qasm import Qasm
---> 30 import qiskit.unroll as unroll
     31 
     32 # Notes:

AttributeError: module 'qiskit' has no attribute 'unroll' `

**Help please , Thanks**

**Comment by rraymondhp** [comment]
Hi, sorry for the late response. Are you using the latest qiskit as below:
https://github.com/QISKit/qiskit-sdk-py

Please make sure that you are installing the latest QuantumProgram. I suspect that your environment refers to the older version of the QuantumProgram.

**Comment by jaygambetta** [comment]
I am going to close this. I updated the readme to say use version r0.3.
