### ISSUE TITLE
quantum_emoticon.ipynb relies on ibmqx5, which has been retired

### ISSUE THREAD

**Issue by holly-cummins** [Qiskit/qiskit-tutorial#401]
## Description
The quantum emoticon tutorial ([`quantum_emoticon.ipynb`](https://github.com/Qiskit/qiskit-tutorial/blob/master/community/hello_world/quantum_emoticon.ipynb)) uses `ibmqx5`. https://www.research.ibm.com/ibm-q/technology/devices/ shows it has been retired, and the closest comparable system is 14 qubits.

The good news is that ASCII is strictly 7 bits, not 8 bits, so the demo should work just as well in 14 qubits. I'll prepare a PR with an update to `ibmq_16_melbourne`.

**Comment by holly-cummins** [comment]
PR #404

**Comment by attp** [comment]
Closing this now that PR #404 has been merged.
