### ISSUE TITLE
Update Backends in tutorial

### ISSUE THREAD

**Issue by hellmersjl3ds** [QISKit/qiskit-tutorial#45]
Hello, I'd like to update the notebook working_with_backends.ipynb with the latest backends.

What's the first step for me to make this contribution?  Create my own branch?

**Comment by rraymondhp** [comment]
Hi, thank you for your interest. 
We'd be glad to have your contribution. 
The first step is to create your own fork (by clicking the `fork` link on the upper right corner). 
Then you can work on the master branch of the fork (or, create a new branch), and do the updates. 
After finishing the updates, you can issue pull request to merge your changes. 

Please let me know if you need any other information.

**Comment by hellmersjl3ds** [comment]
Thanks.  That's enough to get me started.

BTW, do you know if they ever plan an bringing ibmqx2 back online?  It's been down for quite a long time now.

**Comment by hellmersjl3ds** [comment]
OK I created the pull request and it says some conflicts need to be resolved.  They look pretty minor.  Is that something I can do?

**Comment by hellmersjl3ds** [comment]
Changes merged.
