### ISSUE TITLE
Errors from "superposition_and_entanglement"

### ISSUE THREAD

**Issue by dtchang** [QISKit/qiskit-tutorial#47]
TypeError                                 Traceback (most recent call last)
<ipython-input-6-dbdbc3e89bf4> in <module>()
----> 1 plot_histogram(result.get_counts('ground'))

C:\Anaconda\Anaconda3\lib\site-packages\qiskit\_quantumprogram.py in get_counts(self, name)
   1298         """
   1299         try:
-> 1300             return self.get_data(name)['counts']
   1301         except KeyError:
   1302             raise QISKitError('No counts for circuit "{0}"'.format(name))

C:\Anaconda\Anaconda3\lib\site-packages\qiskit\_quantumprogram.py in get_data(self, name)
   1280             for index in range(len(qobj["circuits"])):
   1281                 if qobj["circuits"][index]['name'] == name:
-> 1282                     return self.__result['result'][index]["data"]
   1283         except KeyError:
   1284             raise QISKitError('No data for circuit "{0}"'.format(name))

TypeError: string indices must be integers

-------------------------------------------------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-fee834f272c1> in <module>()
----> 1 plot_histogram(result.get_counts('excited'))

C:\Anaconda\Anaconda3\lib\site-packages\qiskit\_quantumprogram.py in get_counts(self, name)
   1298         """
   1299         try:
-> 1300             return self.get_data(name)['counts']
   1301         except KeyError:
   1302             raise QISKitError('No counts for circuit "{0}"'.format(name))

C:\Anaconda\Anaconda3\lib\site-packages\qiskit\_quantumprogram.py in get_data(self, name)
   1280             for index in range(len(qobj["circuits"])):
   1281                 if qobj["circuits"][index]['name'] == name:
-> 1282                     return self.__result['result'][index]["data"]
   1283         except KeyError:
   1284             raise QISKitError('No data for circuit "{0}"'.format(name))

IndexError: list index out of range

**Comment by diego-plan9** [comment]
Thanks @dtchang - it seems the actual issue might be in input cell 5, which is where the data for the plotting is calculated:
```
In [5]: result = Q_program.execute(circuits, backend=backend, shots=shots, max_credits=3, wait=10, timeout=240, silent=False)
```

Could you please paste the output of that cell in your environment?

**Comment by dtchang** [comment]
Here it is, after 100 seconds:

status = RUNNING (100 seconds)
status = RUNNING (110 seconds)
status = RUNNING (120 seconds)
status = RUNNING (130 seconds)
status = RUNNING (140 seconds)
status = RUNNING (150 seconds)
status = RUNNING (160 seconds)
status = RUNNING (170 seconds)
status = RUNNING (180 seconds)
status = RUNNING (190 seconds)
status = RUNNING (200 seconds)
status = RUNNING (210 seconds)
status = RUNNING (220 seconds)
status = RUNNING (230 seconds)
status = RUNNING (240 seconds)

**Comment by rraymondhp** [comment]
Hello @dtchang 

Is your issue solved with what @diego-plan9 told you? I hope so  and I can close this issue.

**Comment by dtchang** [comment]
No. As I have indicated in my comments, this issue occurred in multiple places ("# Quantum Circuit Superposition", "# Quantum circuit two Hadamards", etc.). Someone from the IBM Q team should try the tutorial from a Windows machine.

**Comment by diego-plan9** [comment]
@dtchang,

could you please try modifying the lines that read:
```
result= Q_program.execute(..., timeout=240, ...)
```

increasing the timeout from 240 to a higher value (for example, 480), and re-run those cells? As mentioned on the other comment, the output you pasted seems to indicate that the execution took too long and time out, as shown by the last lines:

```
status = RUNNING (230 seconds)
status = RUNNING (240 seconds)
```

The lines with `result = Q_program.execute()` "populate" the `results` variable, which is needed by the next lines - and when the ´execute()` calls time out, no results are obtained, which would explain the issue that you are experiencing. Depending on the load of the online backends and other factors, some times the execution might take longer than expected - could you please try with higher timeouts in the hopes of further diagnosing your issue, as it does not seem to be Windows related?

**Comment by dtchang** [comment]
I increased the timeout from 240 to 480 on two of the runs and reran them. The same error occurred on both.

**Comment by rraymondhp** [comment]
I also had the same `timeout` running with Mac. So I believe this is a problem with long queue time.  there are only a few real devices serving many queues, and they may not be able to serve your jobs within the timeout limit.

**Comment by dtchang** [comment]
This is a discouraging news.

**Comment by jaygambetta** [comment]
We are improving the timeout and we had some network issues are you still seeing this error.

**Comment by dtchang** [comment]
Thanks for the effort. I just tried two different runs with the default timeout of 240 seconds. Still encountered this error in both runs.

**Comment by rraymondhp** [comment]
I am now running okay without encountering timeout issues. Would you mind trying again?

**Comment by dtchang** [comment]
I just tried, back from a trip. Two runs still had timeout issues (240 secs). Others finished in time. Glad to see the improvement.

**Comment by rraymondhp** [comment]
Hi, here is my running and it works fine without changing anything in the tutorial:
https://github.com/rraymondhp/qiskit-tutorial/blob/rr-issue47/2_quantum_information/superposition_and_entanglement.ipynb

**Comment by dtchang** [comment]
I just tried. It got worse. The first run didn't proceed beyond 20 seconds. I tried three times.

Please feel free to close this issue. I hope the IBM Q team will completely resolve the timeout issue, at least for the commercial users.

**Comment by rraymondhp** [comment]
Can you show me the file you are running with the error message? This will help the team to identify the issue.

**Comment by jaygambetta** [comment]
@rraymondhp can we close this?

**Comment by rraymondhp** [comment]
I have confirmed that we can run the programs with longer queuing time.  Hence, I close this issue. 

Please reopen the issue if you still experience it.  

Thanks.
