### ISSUE TITLE
missing iterative_phase_estimation_algorithm.ipynb

### ISSUE THREAD

**Issue by tt7533** [QISKit/qiskit-tutorial#63]
There is a link to "iterative_phase_estimation_algorithm.ipynb" in the index notebook but unfortunately I cannot find it anywhere.

**Comment by rraymondhp** [comment]
We mistakenly deleted it and now are working to recover it. Thanks for pointing it out.

**Comment by rraymondhp** [comment]
This issue is addressed by 
https://github.com/QISKit/qiskit-tutorial/pull/69
and
https://github.com/QISKit/qiskit-tutorial/pull/68
