### ISSUE TITLE
Add a Binder badge

### ISSUE THREAD

**Issue by westurner** [QISKit/qiskit-tutorial#64]
## Description

You could add a Binder badge to launch the Jupyter notebooks in a cloud instance

Homepage: https://mybinder.org
Src: https://github.com/jupyterhub/binderhub
Docs: https://binderhub.readthedocs.io/en/latest/

https://github.com/QISKit/qiskit-sdk-py/issues/177

## Your Environment
binder builds cloud containers with repo2docker.
repo2docker will install from requirements.txt and/or environment.yml 
Docs: https://repo2docker.readthedocs.io/en/latest/samples.html#conda-mixed-requirements
Src: https://github.com/jupyter/repo2docker

**Comment by westurner** [comment]
``conda env export -f environment.yml`` 
https://conda.io/docs/user-guide/tasks/manage-environments.html#exporting-the-environment-file

**Comment by rraymondhp** [comment]
Hi,
Thank you very much! This seems cool indeed. Would you be able to explain steps to do that? Perhaps writing a blog or an article on how to run notebooks in the tutorial here will be very nice to people who are not familiar to github and just want to run the tutorials.

**Comment by westurner** [comment]
# Add a Binder badge to README.rst

( Ensure that binder (repo2docker) can install the necessary dependencies with an e.g. environment.yml )

1. Enter the URL and file path into the form at mybinder.org
2. Click the badge icon
3. Copy the RST source to the clipboard
4. Paste the Binder SVG badge link RST source to ``README.rst``:

```restructuredtext
.. image:: https://mybinder.org/badge.svg :target: https://mybinder.org/v2/gh/QISKit/qiskit-tutorial/master?filepath=index.ipynb
```

(Near the top / 'above the fold' of the README?)

# Launch the notebooks in a Binder instance
1. Click on the Binder SVG badge (that says "launch binder") to open /index.ipynb
2. Click any of the (relative) links in index.ipynb to open them in the already-provisioned Binder Docker instance

**Comment by rraymondhp** [comment]
Many thanks! It seems to work pretty well and so easy!!
However, this notebook produces error when run with mybinder
`1_introduction/getting_started.ipynb`

**Comment by westurner** [comment]
Interesting. I jumped ahead to 2. "Superposition and Entanglement" and that seemed to work okay.

The given notebook seems to open in nbviewer just fine; so the JSON isn't a problem with whichever component versions are live on nbviewer.  IDK why there's a Unicode symbol ``\ufeff`` in the JSON? Maybe that's normal? I would need to get to a terminal with hexdump or xxd to take a look.

The complete error message from mybinder.org JupyterHub is:

```
Unreadable Notebook: /home/jovyan/1_introduction/getting_started.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\ufeff{\\n "cells": [\\n {\\n "cell_typ...',)
```

https://github.com/QISKit/qiskit-tutorial/blob/stable/1_introduction/getting_started.ipynb

It shouldn't be necessary, but one can install BinderHub locally (or just repo2docker) to test with. There may be a way to run the ``jupyter convert`` equivalent to runipy at container build time (e.g. after environment.yml or in addition to calling environment.yml) with repo2docker:

```bash
jupyter nbconvert --to notebook --execute mynotebook.ipynb
```

**Comment by rraymondhp** [comment]
Thanks. It appears that the error is due to the file getting_started.ipynb that I fixed just now.
https://github.com/QISKit/qiskit-tutorial/issues/72

**Comment by jaygambetta** [comment]
@diego-plan9 when we are finished with the tutorial rework can you look into this and see what we should do here.

**Comment by westurner** [comment]
- This: https://github.com/QISKit/qiskit-tutorial/issues/64#issuecomment-353984390
- https://mybinder.org/v2/gh/QISKit/qiskit-tutorial/master?filepath=index.ipynb
  - The heading links seem to link to directories instead of .ipynbs?

**Comment by jaygambetta** [comment]
done. A few things that would be good. To get the circuit_drawer working with python and qconfig handled better. These are all on the roadmap for qiskit so im going to close for now.

**Comment by jaygambetta** [comment]
@westurner i got it working with the latex (binder is really nice) and i got the qconfig working by skipping it in the the header and using getpass. Thanks for the suggestions and let me know if you have more improvements.

**Comment by westurner** [comment]
Thanks!
