### ISSUE TITLE
'BinaryOp' object has no attribute 'sym' error

### ISSUE THREAD

**Issue by ionuttamas** [QISKit/qiskit-tutorial#65]
## qp.compile fails

When running the [getting started notebook](https://github.com/QISKit/qiskit-tutorial/blob/stable/1_introduction/getting_started.ipynb) :
```
backend = 'local_qasm_simulator' 
circuits = ['Circuit']  # Group of circuits to execute
qobj=qp.compile(circuits, backend) # Compile your program
```

I get the following error: 'BinaryOp' object has no attribute 'sym'

* Tutorial branch (stable/master): master
* QISKit SDK version: master version
* Python version: 3.6

**Comment by diego-plan9** [comment]
Thanks for reporting, @ionuttamas ! As https://github.com/QISKit/qiskit-sdk-py/pull/171 has just been merged, can you check if the current `master` version of the SDK solves the issue you described on your environment?

**Comment by ionuttamas** [comment]
Yup works great now. Thanks!
