### ISSUE TITLE
Unreadable Notebook: qiskit-tutorial-master/1_introduction/getting_started.ipynb

### ISSUE THREAD

**Issue by neilnelson** [QISKit/qiskit-tutorial#72]
On http://localhost:8888/notebooks/qiskit-tutorial-master/index.ipynb#section1

Link
Getting started with QISKit SDK - how to use QISKit SDK.

Obtained
Unreadable Notebook: /home/nnelson/environments/qiskit-tutorial-master/1_introduction/getting_started.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\ufeff{\\n "cells": [\\n {\\n "cell_typ...',)

New installation from instructions at
From https://github.com/QISKit/qiskit-sdk-py/blob/master/doc/install.rst

Using tutorial
https://github.com/QISKit/qiskit-tutorial/archive/master.zip

From python3 environment
pip install qiskit

Python 3.5.2

Xubuntu 16.04.3 LTS

The next link in section 1 works.
Understanding the different backends - how to get information about the connected backends.

jupyter --version
4.4.0

**Comment by rraymondhp** [comment]
Thanks for pointing this. I have fixed the file with this PR:
https://github.com/QISKit/qiskit-tutorial/pull/73
Please update your master branch and see if it works. It seems that the stable branch has no problem.

**Comment by neilnelson** [comment]
Downloaded https://github.com/QISKit/qiskit-tutorial/archive/master.zip

Loaded the new version into Jupyter.

Clicked on the Getting started with QISKit SDK - how to use QISKit SDK.

Worked OK.
