### ISSUE TITLE
Suggestion on managing API and URL via environment vars for real devices

### ISSUE THREAD

**Issue by EvanKepner** [QISKit/qiskit-tutorial#74]
Hey just started this tutorial, love that you are putting this together. One suggestion for the introduction when it comes to the real device configuration - have the users put their API key and the URL into environment variables instead of into local Python files. This removes the risk of people accidentally committing to public repos and exposing their keys. 

The following would be changed:

1. README - in section 4 instruct the user to setup an `IBMAPI` and `IBMURL` environment variable e.g. in their `.bash_profile` or similar using `export` statements.
2. In the Introduction - Getting Started notebook change the imports to remove `Qconfig` and instead `import os`.
3. In the Introduction - Getting Started notebook change the "Real Devices" section to get the environment variables instead e.g. 

```python
qp.set_api(os.getenv("IBMAPI"), os.getenv("IBMURL"))
```

**Comment by rraymondhp** [comment]
Hi, many thanks! This is a very nice suggestion. I wonder how to do a similar thing with Windows environment. I think this should also be considered at `qiskit-sdk-py`.

**Comment by EvanKepner** [comment]
For sure! I think it varies by Windows version (unfortunately I don't have a system to test on) where you can set environment variables under the advanced system settings. 

If you are open to accepting pull requests I would be happy to add instructions in the README to provide the alternative example with `os.getenv()`. If the `QConfig.py` file is used in multiple notebooks it could take some time to update them all, but that way the audience is aware of the option if they want to make changes in their own copies of the notebooks.

**Comment by rraymondhp** [comment]
Many thanks! Please feel free to add instructions in the README. I personally agree to have more options and make things simpler if possible. I think your suggestion is a good way towards, but we need to discuss it with those in `qiskit-sdk-py` too. 

But please understand that it will be one of the options at the moment because we think having all in python thru the `QConfig.py` is essential.

**Comment by EvanKepner** [comment]
Excellent, I'll put in a pull request for review. Thanks! If keeping the`QConfig.py` is essential I'll move the suggestion to changing that file instead of the notebook e.g. 

```python
APItoken = 'my token from the Quantum Experience'
config = {'url': 'https://quantumexperience.ng.bluemix.net/api'}

if 'APItoken' not in locals():
    raise Exception('Please set up your access token. See Qconfig.py.')
```

Would now optionally become:

```python
import os

APItoken = os.getenv("IBMQE_API")  # if you have set this via an environment variable
config = {'url': 'https://quantumexperience.ng.bluemix.net/api'}

if 'APItoken' not in locals():
    raise Exception('Please set up your access token. See Qconfig.py.')
```

This way the `QConfig` does not need to be removed from the notebooks, but you are also not storing the API key in a file that may become part of a public repo.

**Comment by rraymondhp** [comment]
I have merged the PR that deals with this issue. Thank you very much and looking forward to your next contribution.

**Comment by EvanKepner** [comment]
Awesome - thank you! I'm looking forward to doing more of the tutorials :smile:
