### ISSUE TITLE
Added circuit figures once qiskit-sdk-py supports figure generation from qasm

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#76]
## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by jaygambetta** [comment]
I agree and removing the figures saved in images.

**Comment by jaygambetta** [comment]
This is done with the circuit drawer. I am going to close this as the only thing that remains is the same as
