### ISSUE TITLE
Set more credits (or no credit spend) for reviewers of the tutorials

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#83]
## Description

To review tutorials, the reviewers must test the experiments on real devices many times. They need more credits to do that. Either give them more credits or identify them so they do not need to spend credits for testing.

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by orrinjelo** [comment]
Also, some of the timeouts sometimes aren't waiting long enough, and you get a 403 code in return.  That costs some pretty credit too.

**Comment by jaygambetta** [comment]
@francabrera i agree with @rraymondhp is there someway that we can set up a tutorial user for checking the tutorials work correctly.

Or i still think its best that we have cache runs for the tutorial.

**Comment by rraymondhp** [comment]
This is already solved.
