### ISSUE TITLE
Use README.md for index and generate index automatically (with ipynb or other formats)

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#84]
## Description

The index files do not contain executable codes. Markdown formats will suffice, 

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by jaygambetta** [comment]
I dont understand this could you give more information.

**Comment by attp** [comment]
This has been discussed on Slack and is now closed. We have one index file with links to all the reference tutorials, and people can browse the appendix ones through the folder structure.
