### ISSUE TITLE
reworking the tutorial so that it is easier to manage

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit-tutorial#92]
We are going to split the tutorial into three sections. 

We are going to add to a WIP PR that i will set up and if you want to help in the rework that would be great. Either you can help by commenting here or helping in the content. The names are the assigned people that are going to coordinate the different sections. 

# sections

* **Hello World**: Since quantum computing is so new, we want to find the best *Hello Quantum World* program and welcome submissions here. 
* **Reference**: These notebooks demonstrate how to use QISKit and explore quantum information science, acting as a reference book for QISKit. They will be kept up to date with QISKit SDK updates. They are organised into various topics:
  1. Getting started with QISKit  (me)
    - Getting started
    - Working with backends (including compiling and running)
    - Using different gates
    - Visualisation of quantum states
  2. Introduction to quantum information science  @attp 
    - Superposition and entanglement
    - Entanglement revisited
    - Quantum teleportation and superdense coding
  3. Understanding your quantum computer @dtmcclure 
    - Relaxation and decoherence
    - Quantum tomography
    - Random Benchmarking # to be written
  4. Working an approximate quantum quantum computers  @adcorcol 
    - Variational Quantum Eigensolver
    - Small error correcting codes # to be written
    - Error mitigation # to be written
  5. Examples of quantum algorithms @rraymondhp 
    - Phase estimation
    - Deutsch–Jozsa algorithm
    - Bernstein-Vazirani algorithm
    - Simon's algorithm
    - Grover's algorithm
    - Shor's algorithm
  6. Having fun with quantum computers 
    - Battleships
    - 
    - 
* **Appendix** This is where the rest of the tutorials are. They are not guaranteed to work with the latest version of the QISKit SDK. They are organised into various topics:
  1. Advanced QISKit features
  2. More on quantum information
  3. Further quantum algorithms and applications
  4. Everything else

**Comment by jaygambetta** [comment]
To help out please commit to https://github.com/jaygambetta/qiskit-tutorial.

**Comment by rraymondhp** [comment]
@jaygambetta  Would you mind updating the getting started QISKit tutorials? 

@dtmcclure  Do you think you can complete the random benchmarking within this week? 

@adcorcol  Do you think you can complete the rest of tutorials for approximate quantum computers

**Comment by dtmcclure** [comment]
@rraymondhp I believe others are still working on adding functionality to the SDK's tools.qcvv module to enable a randomized benchmarking notebook to be written. I'll be happy to help out with the notebook once that's ready.

**Comment by jaygambetta** [comment]
I started the Merge #118 . I am going to close this so that we can make little prs to fix the remainder of issues. The new version is in master and i have made the old version another branch that we can keep around until we are finished.
