### ISSUE TITLE
Guidelines for installing dependencies like pdflatex etc.

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/qiskit-tutorial#95]
## Description

A list of dependencies on getting started tutorial and how to install them (if possible). 

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by ajavadia** [comment]
Here's what is needed for the circuit drawing part. I will write a separate tutorial on circuit visualization.

`pip install pillow`
`pip install pdf2image`
download poppler: 
[(Windows)](https://sourceforge.net/projects/poppler-win32/)
[(Mac)](http://macappstore.org/poppler/)
Linux: `sudo apt install poppler-utils`

**Comment by rraymondhp** [comment]
Thanks! This is really helpful.

**Comment by rraymondhp** [comment]
Ninad also told me a script installing all dependencies as here:
https://github.ibm.com/nsathaye/qiskit_dsx/blob/master/qiskit_dependencies.sh

**Comment by sathayen** [comment]
@ajavadia on Linux I required `texlive` packages But  installing those packages need quite a bit of additional space.  Is there any lightweight alternative to the circuite visualization? 
I will create a public version of the script I have written ( @rraymondhp mentioned this in earlier note) Essentially this is what it has -- 

```pip install qiskit
pip install pdf2image

apt-get update
apt-get install -y poppler-utils

# ~ 1.2 GB  (texlive-latex-base= 307MB) 
apt-get install texlive-latex-base texlive-pictures texlive-latex-extra ```

**Comment by ajavadia** [comment]
The current circuit plotter goes like qasm->latex->pdf->png 
We have an open issue to make the dependencies lighter:
https://github.com/QISKit/qiskit-sdk-py/issues/311

**Comment by jaygambetta** [comment]
@ajavadia what is the status of this. Rather than a tutorial can we just make sure we add to the INSTALL a link for making sure you have the requirements as i use them heavy in the new tutorials
