### ISSUE TITLE
[CallForParticipation] Tutorials for Grover's search, Simon's and Shor's algorithms

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-tutorial#97]
## Description

Show tutorials of well-known quantum algorithms.

## Your Environment

* Tutorial branch (stable/master):
* QISKit SDK version:
* Python version:

**Comment by jaygambetta** [comment]
I agree we need to get these in the algorithm section. Hopefully we can find someone with time to make them.

**Comment by rraymondhp** [comment]
https://github.com/Qiskit/qiskit-tutorial/pull/131

**Comment by adjs** [comment]
Great tutorials! In #253 I removed typos and made minor corrections in the equations and description of the Simon's algorithm.

**Comment by amantamirat** [comment]
I want to participate and I had implement Grover's algorithm, what is the next.

**Comment by attp** [comment]
I think this should be closed now. We have tutorials for Grover's, Shor's and Simon's algorithms, once PR #131 is approved.

**Comment by jaygambetta** [comment]
I agree
